[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback so react-router-dom works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
